version: "3.9"
services:
  webapi:
    build:
      context: .
      dockerfile: FiapBlog.WebAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionString: "Server=db,1433;Database=InstaDb;User=sa;Password=#Admin123;TrustServerCertificate=true"
    networks:
      - fiap-blog
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "#Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - fiap-blog
    volumes:
      - /c/sqlserver:/var/opt/mssql/data
  
networks:
  fiap-blog:
      name: fiap-blog